"""
Trip Wizard – Project Explainer PDF
Generated by Claude Code
"""

import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable, KeepTogether
)
from reportlab.platypus.flowables import Flowable
from reportlab.graphics.shapes import Drawing, Rect, String, Line, Circle, Polygon
from reportlab.graphics import renderPDF
from reportlab.lib.colors import HexColor
from datetime import date

# ─── Color Palette ───────────────────────────────────────────────────────────
C_BLUE      = HexColor('#2563EB')
C_BLUE_LIGHT = HexColor('#DBEAFE')
C_BLUE_MID  = HexColor('#93C5FD')
C_GREEN     = HexColor('#16A34A')
C_GREEN_LIGHT = HexColor('#DCFCE7')
C_PURPLE    = HexColor('#7C3AED')
C_PURPLE_LIGHT = HexColor('#EDE9FE')
C_ORANGE    = HexColor('#EA580C')
C_ORANGE_LIGHT = HexColor('#FFEDD5')
C_GRAY      = HexColor('#6B7280')
C_GRAY_LIGHT = HexColor('#F3F4F6')
C_SLATE     = HexColor('#1E293B')
C_YELLOW_LIGHT = HexColor('#FEFCE8')
C_YELLOW_BORDER = HexColor('#FDE047')
C_TEAL      = HexColor('#0D9488')
C_TEAL_LIGHT = HexColor('#CCFBF1')
C_RED_LIGHT = HexColor('#FEE2E2')
C_PAGE_BG   = HexColor('#F8FAFC')
C_WHITE     = colors.white
C_BLACK     = colors.black

PAGE_W, PAGE_H = letter
MARGIN = 0.75 * inch
CONTENT_W = PAGE_W - 2 * MARGIN

OUTPUT_PATH = os.path.join(os.path.dirname(__file__), 'tripWizard-explained.pdf')

# ─── Custom Flowables ────────────────────────────────────────────────────────

class ColorBar(Flowable):
    """Full-width colored horizontal divider bar."""
    def __init__(self, color, height=4, width=None):
        Flowable.__init__(self)
        self.bar_color = color
        self.bar_height = height
        self.bar_width = width
    def wrap(self, aW, aH):
        return (self.bar_width or aW, self.bar_height)
    def draw(self):
        w = self.bar_width or CONTENT_W
        self.canv.setFillColor(self.bar_color)
        self.canv.rect(0, 0, w, self.bar_height, fill=1, stroke=0)

class SectionHeader(Flowable):
    """Large section header with colored left accent bar."""
    def __init__(self, text, color=C_BLUE, width=None):
        Flowable.__init__(self)
        self.text = text
        self.color = color
        self.hdr_width = width
    def wrap(self, aW, aH):
        return (self.hdr_width or aW, 36)
    def draw(self):
        w = self.hdr_width or CONTENT_W
        self.canv.setFillColor(self.color)
        self.canv.rect(0, 6, 5, 24, fill=1, stroke=0)
        self.canv.setFillColor(C_GRAY_LIGHT)
        self.canv.rect(5, 0, w - 5, 34, fill=1, stroke=0)
        self.canv.setFillColor(C_SLATE)
        self.canv.setFont('Helvetica-Bold', 16)
        self.canv.drawString(14, 11, self.text)

class GlossaryBox(Flowable):
    """Yellow-background glossary box."""
    def __init__(self, terms, width=None):
        Flowable.__init__(self)
        self.terms = terms  # list of (term, definition)
        self.box_width = width
    def wrap(self, aW, aH):
        w = self.box_width or aW
        h = 22 + len(self.terms) * 18 + 10
        return (w, h)
    def draw(self):
        w = self.box_width or CONTENT_W
        h = 22 + len(self.terms) * 18 + 10
        # background
        self.canv.setFillColor(C_YELLOW_LIGHT)
        self.canv.roundRect(0, 0, w, h, 6, fill=1, stroke=1)
        self.canv.setStrokeColor(C_YELLOW_BORDER)
        self.canv.roundRect(0, 0, w, h, 6, fill=0, stroke=1)
        # header
        self.canv.setFillColor(HexColor('#92400E'))
        self.canv.setFont('Helvetica-BoldOblique', 9)
        self.canv.drawString(10, h - 16, '📖 Key Terms')
        # terms
        y = h - 32
        for term, defn in self.terms:
            self.canv.setFont('Helvetica-Bold', 8)
            self.canv.setFillColor(C_SLATE)
            self.canv.drawString(10, y, f'{term}')
            self.canv.setFont('Helvetica', 8)
            self.canv.setFillColor(C_GRAY)
            self.canv.drawString(10 + self.canv.stringWidth(term, 'Helvetica-Bold', 8) + 6, y, f'→  {defn}')
            y -= 18

class FileBadge(Flowable):
    """Colored pill badge for a filename."""
    def __init__(self, name, color, bg_color, width=None):
        Flowable.__init__(self)
        self.name = name
        self.fg = color
        self.bg = bg_color
    def wrap(self, aW, aH):
        return (aW, 20)
    def draw(self):
        self.canv.setFillColor(self.bg)
        self.canv.roundRect(0, 2, 220, 16, 4, fill=1, stroke=0)
        self.canv.setFillColor(self.fg)
        self.canv.setFont('Helvetica-Bold', 9)
        self.canv.drawString(8, 6, self.name)

class FlowchartBox(Flowable):
    """A vertical flowchart of execution steps."""
    def __init__(self, steps, width=None):
        Flowable.__init__(self)
        self.steps = steps  # list of (label, type) where type is 'action'|'decision'|'start'|'end'
        self.chart_width = width or CONTENT_W
    def wrap(self, aW, aH):
        total = len(self.steps) * 60 + 20
        return (self.chart_width, total)
    def draw(self):
        w = self.chart_width
        cx = w / 2
        y = len(self.steps) * 60 + 10
        box_w = min(w - 80, 340)
        box_h = 38

        for i, (label, stype) in enumerate(self.steps):
            by = y - 50
            bx = cx - box_w / 2

            # Arrow down (except first)
            if i > 0:
                self.canv.setStrokeColor(C_GRAY)
                self.canv.setLineWidth(1.5)
                self.canv.line(cx, by + box_h + 12, cx, by + box_h + 2)
                # arrowhead
                self.canv.setFillColor(C_GRAY)
                self.canv.polygon([cx-4, by+box_h+4, cx+4, by+box_h+4, cx, by+box_h-2], fill=1)

            # Box
            if stype == 'start' or stype == 'end':
                fill = HexColor('#166534')
                txt_color = C_WHITE
                self.canv.setFillColor(fill)
                self.canv.roundRect(bx, by, box_w, box_h, box_h/2, fill=1, stroke=0)
            elif stype == 'decision':
                fill = HexColor('#FEF9C3')
                stroke = HexColor('#CA8A04')
                txt_color = HexColor('#713F12')
                self.canv.setFillColor(fill)
                self.canv.setStrokeColor(stroke)
                self.canv.setLineWidth(1.5)
                # diamond shape (approximated as rotated rect)
                mid_x = bx + box_w/2
                pts = [mid_x, by+box_h, bx+box_w, by+box_h/2, mid_x, by, bx, by+box_h/2]
                self.canv.polygon(pts, fill=1, stroke=1)
            else:
                fill = C_BLUE_LIGHT
                txt_color = C_BLUE
                self.canv.setFillColor(fill)
                self.canv.setStrokeColor(C_BLUE_MID)
                self.canv.setLineWidth(1)
                self.canv.roundRect(bx, by, box_w, box_h, 6, fill=1, stroke=1)

            # Text
            font = 'Helvetica-Bold' if stype in ('start','end') else 'Helvetica'
            font_size = 9
            self.canv.setFont(font, font_size)
            self.canv.setFillColor(txt_color if stype in ('start','end','decision') else C_SLATE)
            # wrap label to fit
            text = label
            text_w = self.canv.stringWidth(text, font, font_size)
            while text_w > box_w - 16 and len(text) > 10:
                text = text[:-4] + '…'
                text_w = self.canv.stringWidth(text, font, font_size)
            self.canv.drawCentredString(cx, by + box_h/2 - 5, text)

            y -= 60

class ConnectionDiagram(Flowable):
    """Box-and-arrow diagram showing how files connect."""
    def __init__(self, boxes, arrows, width=None):
        Flowable.__init__(self)
        self.boxes = boxes   # list of (id, label, x, y, color, text_color)
        self.arrows = arrows  # list of (from_id, to_id, label)
        self.diag_width = width or CONTENT_W
        # find max y
        max_y = max(b[3] for b in boxes) if boxes else 0
        self.diag_height = max_y + 80
    def wrap(self, aW, aH):
        return (self.diag_width, self.diag_height)
    def draw(self):
        w = self.diag_width
        scale_x = w / 600.0
        box_positions = {}

        # Draw boxes
        BOX_W, BOX_H = 120, 32
        for bid, label, bx, by, bg, fg in self.boxes:
            rx = bx * scale_x
            ry = self.diag_height - by - BOX_H
            box_positions[bid] = (rx, ry, BOX_W * scale_x, BOX_H)
            self.canv.setFillColor(bg)
            self.canv.setStrokeColor(fg)
            self.canv.setLineWidth(1.5)
            self.canv.roundRect(rx, ry, BOX_W * scale_x, BOX_H, 5, fill=1, stroke=1)
            self.canv.setFillColor(fg)
            self.canv.setFont('Helvetica-Bold', 7.5)
            tw = self.canv.stringWidth(label, 'Helvetica-Bold', 7.5)
            max_tw = BOX_W * scale_x - 8
            lbl = label
            while self.canv.stringWidth(lbl, 'Helvetica-Bold', 7.5) > max_tw and len(lbl) > 5:
                lbl = lbl[:-4] + '…'
            self.canv.drawCentredString(rx + BOX_W * scale_x / 2, ry + BOX_H/2 - 5, lbl)

        # Draw arrows
        for fid, tid, lbl in self.arrows:
            if fid not in box_positions or tid not in box_positions:
                continue
            fx, fy, fw, fh = box_positions[fid]
            tx, ty, tw2, th = box_positions[tid]
            # Start from bottom center of from box, end at top center of to box
            sx = fx + fw / 2
            sy = fy
            ex = tx + tw2 / 2
            ey = ty + th
            self.canv.setStrokeColor(C_GRAY)
            self.canv.setLineWidth(1)
            self.canv.line(sx, sy, ex, ey)
            # arrowhead
            self.canv.setFillColor(C_GRAY)
            angle_x = ex - sx
            angle_y = ey - sy
            length = (angle_x**2 + angle_y**2) ** 0.5
            if length > 0:
                ux, uy = angle_x/length, angle_y/length
                px, py = -uy, ux
                self.canv.polygon([
                    ex, ey,
                    ex - 6*ux + 3*px, ey - 6*uy + 3*py,
                    ex - 6*ux - 3*px, ey - 6*uy - 3*py,
                ], fill=1)
            # label
            if lbl:
                mx, my = (sx+ex)/2, (sy+ey)/2
                self.canv.setFillColor(C_GRAY)
                self.canv.setFont('Helvetica-Oblique', 6.5)
                self.canv.drawCentredString(mx, my + 3, lbl)


class FileTreeBox(Flowable):
    """Visual file tree with color-coded files."""
    def __init__(self, entries, width=None):
        Flowable.__init__(self)
        self.entries = entries  # list of (indent, name, color, description)
        self.box_width = width or CONTENT_W
        self.row_h = 22
    def wrap(self, aW, aH):
        h = len(self.entries) * self.row_h + 20
        return (self.box_width, h)
    def draw(self):
        w = self.box_width
        y = len(self.entries) * self.row_h + 8
        # Background
        self.canv.setFillColor(HexColor('#0F172A'))
        self.canv.roundRect(0, 0, w, y + 8, 6, fill=1, stroke=0)

        for indent, name, color, desc in self.entries:
            y -= self.row_h
            x = 12 + indent * 16
            # Dot indicator
            if color:
                self.canv.setFillColor(color)
                self.canv.circle(x + 4, y + 8, 4, fill=1, stroke=0)
                name_x = x + 14
            else:
                name_x = x + 4

            # Filename
            self.canv.setFont('Helvetica-Bold', 9)
            self.canv.setFillColor(HexColor('#F1F5F9') if color else HexColor('#94A3B8'))
            self.canv.drawString(name_x, y + 4, name)

            # Description
            if desc:
                name_w = self.canv.stringWidth(name, 'Helvetica-Bold', 9)
                self.canv.setFont('Helvetica-Oblique', 7.5)
                self.canv.setFillColor(HexColor('#64748B'))
                max_desc_x = w - 16
                desc_x = name_x + name_w + 10
                if desc_x < max_desc_x:
                    desc_text = desc
                    while self.canv.stringWidth(desc_text, 'Helvetica-Oblique', 7.5) > max_desc_x - desc_x and len(desc_text) > 8:
                        desc_text = desc_text[:-4] + '…'
                    self.canv.drawString(desc_x, y + 4, '→  ' + desc_text)


# ─── Page templates ──────────────────────────────────────────────────────────

def on_page(canvas, doc):
    """Header and page number on every page after the cover."""
    if doc.page == 1:
        return
    canvas.saveState()
    canvas.setFillColor(C_BLUE)
    canvas.rect(0, PAGE_H - 28, PAGE_W, 28, fill=1, stroke=0)
    canvas.setFillColor(C_WHITE)
    canvas.setFont('Helvetica-Bold', 9)
    canvas.drawString(MARGIN, PAGE_H - 18, '🧙 Trip Wizard — Project Explainer')
    canvas.setFont('Helvetica', 9)
    canvas.drawRightString(PAGE_W - MARGIN, PAGE_H - 18, f'Page {doc.page}  •  Generated {date.today().strftime("%B %d, %Y")}')
    canvas.restoreState()


# ─── Content builders ────────────────────────────────────────────────────────

def cover_page(styles):
    elems = []
    elems.append(Spacer(1, 1.2*inch))

    # Big wizard emoji area
    drawing = Drawing(CONTENT_W, 120)
    bg = Rect(0, 0, CONTENT_W, 120, fillColor=C_BLUE, strokeColor=None)
    drawing.add(bg)
    icon = String(CONTENT_W/2, 55, '🧙', fontSize=56, textAnchor='middle', fillColor=colors.white)
    drawing.add(icon)
    elems.append(drawing)
    elems.append(Spacer(1, 0.3*inch))

    title_style = ParagraphStyle('Cover', fontName='Helvetica-Bold', fontSize=34,
                                  textColor=C_SLATE, alignment=TA_CENTER, spaceAfter=10)
    sub_style = ParagraphStyle('CoverSub', fontName='Helvetica', fontSize=14,
                                textColor=C_GRAY, alignment=TA_CENTER, spaceAfter=6)
    elems.append(Paragraph('Trip Wizard', title_style))
    elems.append(Paragraph('Your AI-Powered Travel Planning App', sub_style))
    elems.append(Spacer(1, 0.3*inch))

    # Badge row
    badge_data = [['Built with', 'React', '+', 'Node.js', '+', 'Gemini AI']]
    badge_table = Table(badge_data, colWidths=[70, 65, 18, 65, 18, 80],
                        style=TableStyle([
                            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
                            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                            ('FONTNAME', (0,0), (0,0), 'Helvetica'),
                            ('FONTNAME', (1,0), (1,0), 'Helvetica-Bold'),
                            ('FONTNAME', (3,0), (3,0), 'Helvetica-Bold'),
                            ('FONTNAME', (5,0), (5,0), 'Helvetica-Bold'),
                            ('FONTSIZE', (0,0), (-1,-1), 11),
                            ('TEXTCOLOR', (0,0), (0,0), C_GRAY),
                            ('TEXTCOLOR', (1,0), (1,0), C_BLUE),
                            ('TEXTCOLOR', (3,0), (3,0), C_GREEN),
                            ('TEXTCOLOR', (5,0), (5,0), C_PURPLE),
                            ('BACKGROUND', (1,0), (1,0), C_BLUE_LIGHT),
                            ('BACKGROUND', (3,0), (3,0), C_GREEN_LIGHT),
                            ('BACKGROUND', (5,0), (5,0), C_PURPLE_LIGHT),
                            ('ROUNDEDCORNERS', [4]),
                            ('TOPPADDING', (0,0), (-1,-1), 6),
                            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                            ('LEFTPADDING', (1,0), (1,0), 10),
                            ('RIGHTPADDING', (1,0), (1,0), 10),
                            ('LEFTPADDING', (3,0), (3,0), 10),
                            ('RIGHTPADDING', (3,0), (3,0), 10),
                            ('LEFTPADDING', (5,0), (5,0), 10),
                            ('RIGHTPADDING', (5,0), (5,0), 10),
                        ]))
    elems.append(badge_table)
    elems.append(Spacer(1, 0.4*inch))

    date_style = ParagraphStyle('Date', fontName='Helvetica', fontSize=10,
                                 textColor=C_GRAY, alignment=TA_CENTER)
    elems.append(Paragraph(f'Generated on {date.today().strftime("%B %d, %Y")}', date_style))
    elems.append(PageBreak())
    return elems


def what_it_does_page(styles):
    body = ParagraphStyle('Body', fontName='Helvetica', fontSize=10.5,
                           textColor=C_SLATE, leading=17, spaceAfter=12)
    bold = ParagraphStyle('Bold', fontName='Helvetica-Bold', fontSize=10.5,
                           textColor=C_SLATE, leading=17)
    elems = []
    elems.append(Spacer(1, 0.2*inch))
    elems.append(SectionHeader('What This Project Does', C_BLUE))
    elems.append(Spacer(1, 0.2*inch))

    elems.append(Paragraph(
        '<b>Trip Wizard is a web application that helps you plan and organize travel itineraries '
        'with the help of artificial intelligence.</b> Instead of juggling between Google Maps, '
        'weather apps, and travel blogs, Trip Wizard brings everything together in one place — '
        'your trips, daily plans, live weather, nearby places, and an AI assistant that knows '
        'exactly where you are and what you\'re doing.', body))

    elems.append(Paragraph(
        'The problem it solves is simple: planning a trip day-by-day is overwhelming. You need '
        'to know the weather, find things to do, pick restaurants, figure out the best order to '
        'visit places so you\'re not crisscrossing the city — and do all of this while managing '
        'your accommodation and travel companions. Trip Wizard handles all of that in one app.', body))

    elems.append(Paragraph(
        'When you open the app, you create a trip (e.g., "Rome Adventure — June 10–17, 2025"). '
        'Then, day by day, you add entries: where you\'ll be, where you\'re staying, and what '
        'activities you plan. The app shows you live weather for each location, lists nearby '
        'restaurants and attractions (pulled straight from Google Maps), and gives you an '
        'AI-powered chat assistant you can ask questions like "What should we do tonight?" or '
        '"Give me a full itinerary for my remaining days."', body))

    elems.append(Paragraph(
        'The most powerful feature is the <b>AI Schedule Optimizer</b>. Once you\'ve added your '
        'activities for a day, you click one button and the AI reorganizes your schedule to '
        'minimize crowds, take advantage of good weather windows, and respect typical opening '
        'hours — things like "go to the outdoor market early before it gets crowded" or '
        '"visit the museum in the afternoon when rain is most likely."', body))

    # Feature summary table
    elems.append(Spacer(1, 0.15*inch))
    features = [
        ['Feature', 'What it does'],
        ['Trip Management', 'Create, edit, and delete trips with dates and traveler info'],
        ['Day Planning', 'Log daily locations, accommodation, and activities'],
        ['Live Weather', 'Real-time weather + 5-day forecast for any location worldwide'],
        ['Nearby Places', 'Browse restaurants, attractions & museums near your location'],
        ['AI Chat Assistant', 'Ask travel questions in plain English — AI knows your itinerary'],
        ['Schedule Optimizer', 'AI reorders your activities for the most efficient, enjoyable day'],
        ['Visual Timeline', 'See your day as a timeline with crowd/weather indicators'],
    ]
    t = Table(features, colWidths=[160, CONTENT_W - 165])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), C_BLUE),
        ('TEXTCOLOR', (0,0), (-1,0), C_WHITE),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (0,-1), 'Helvetica-Bold'),
        ('FONTNAME', (1,1), (1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [C_WHITE, C_GRAY_LIGHT]),
        ('GRID', (0,0), (-1,-1), 0.5, HexColor('#CBD5E1')),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
    ]))
    elems.append(t)
    elems.append(Spacer(1, 0.15*inch))
    elems.append(Paragraph(
        'The app works even without any API keys — it runs in "demo mode" with realistic sample '
        'data so you can explore every feature. Add your own API keys to unlock real AI responses, '
        'actual weather, and live Google Maps data.', body))
    elems.append(PageBreak())
    return elems


def project_map_page(styles):
    elems = []
    elems.append(Spacer(1, 0.2*inch))
    elems.append(SectionHeader('Project Map — Files & Folders', C_GREEN))
    elems.append(Spacer(1, 0.15*inch))

    note_style = ParagraphStyle('Note', fontName='Helvetica-Oblique', fontSize=9,
                                  textColor=C_GRAY, spaceAfter=10)
    elems.append(Paragraph('Every file in the project, color-coded by role:', note_style))

    # Tree entries: (indent, name, color, description)
    tree = [
        (0, 'tripWizard/', None, 'Project root'),
        (1, 'server/', None, 'Backend — the "engine" running on your computer'),
        (2, 'index.js', C_BLUE, 'Entry point — starts the server'),
        (2, 'routes/', None, 'Web addresses the app responds to'),
        (3, 'trips.js', C_GREEN, 'CRUD for trips & days'),
        (3, 'chat.js', C_GREEN, 'AI chat & schedule optimizer'),
        (3, 'weather.js', C_GREEN, 'Weather data'),
        (3, 'places.js', C_GREEN, 'Nearby places'),
        (2, 'services/', None, 'External API integrations'),
        (3, 'gemini.js', C_PURPLE, 'Google Gemini AI brain'),
        (3, 'claude.js', C_PURPLE, 'Claude AI (alternative AI)'),
        (3, 'weather.js', C_TEAL, 'OpenWeatherMap integration'),
        (3, 'places.js', C_TEAL, 'Google Places integration'),
        (2, 'db/', None, 'Data storage'),
        (3, 'storage.js', C_ORANGE, 'Read/write trips.json file'),
        (1, 'client/', None, 'Frontend — what users see in the browser'),
        (2, 'src/', None, ''),
        (3, 'main.jsx', C_BLUE, 'Frontend entry point'),
        (3, 'App.jsx', C_BLUE, 'Routing & layout wrapper'),
        (3, 'pages/', None, 'Full page views'),
        (4, 'Home.jsx', C_ORANGE, 'Trip list & create trip'),
        (4, 'TripDetail.jsx', C_ORANGE, 'Single trip view & calendar'),
        (4, 'DayPage.jsx', C_ORANGE, 'Day details, weather, places, timeline'),
        (4, 'ExplorePage.jsx', C_ORANGE, 'Explore places & search'),
        (3, 'components/', None, 'Reusable UI building blocks'),
        (4, 'Navbar.jsx', C_ORANGE, 'Top navigation bar'),
        (4, 'FloatingChat.jsx', C_ORANGE, 'The AI chat popup panel'),
        (4, 'WeatherWidget.jsx', C_ORANGE, 'Weather display card'),
        (4, 'PlacesPanel.jsx', C_ORANGE, 'Nearby places browser'),
        (4, 'Timeline.jsx', C_ORANGE, 'Daily schedule timeline'),
        (4, 'TripCard.jsx', C_ORANGE, 'Trip summary card'),
        (4, 'TripForm.jsx', C_ORANGE, 'Create-trip form'),
        (4, 'DayForm.jsx', C_ORANGE, 'Add-day form'),
        (4, 'PlanCard.jsx', C_ORANGE, 'AI-generated itinerary card'),
        (3, 'context/', None, ''),
        (4, 'ChatContext.jsx', C_GRAY, 'Global chat state (open/messages)'),
        (3, 'utils/', None, ''),
        (4, 'api.js', C_GRAY, 'All HTTP calls to the backend'),
        (1, 'data/', None, ''),
        (2, 'trips.json', C_PURPLE, 'Your trips — saved here automatically'),
        (1, '.env.example', C_PURPLE, 'Template for API keys'),
    ]

    elems.append(FileTreeBox(tree, width=CONTENT_W))
    elems.append(Spacer(1, 0.2*inch))

    # Legend
    legend_data = [
        [' ', '🔵 Blue = Entry point (where the program starts)',
         '🟢 Green = Data & logic handling'],
        [' ', '🟣 Purple = Configuration & AI services',
         '🟠 Orange = User interface components'],
        [' ', '🩵 Teal = External API wrappers',
         '⚫ Gray = Utility & helper files'],
    ]
    legend_t = Table(legend_data, colWidths=[10, CONTENT_W/2 - 5, CONTENT_W/2 - 5])
    legend_t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), C_GRAY_LIGHT),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 8),
        ('TEXTCOLOR', (0,0), (-1,-1), C_SLATE),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
    ]))
    elems.append(legend_t)
    elems.append(PageBreak())
    return elems


def connections_page(styles):
    elems = []
    elems.append(Spacer(1, 0.2*inch))
    elems.append(SectionHeader('How the Files Connect', C_PURPLE))
    elems.append(Spacer(1, 0.15*inch))

    note_style = ParagraphStyle('Note', fontName='Helvetica', fontSize=9.5,
                                  textColor=C_GRAY, spaceAfter=12, leading=15)
    elems.append(Paragraph(
        'The diagram below shows how the major pieces of Trip Wizard talk to each other. '
        'Arrows mean "this part sends a request to / relies on that part."', note_style))

    # boxes: (id, label, x, y, bg_color, text_color)
    # x and y are in a 0-600 coordinate space, y from top
    boxes = [
        ('browser',  'Your Browser',         230, 30,  C_BLUE,         C_WHITE),
        ('app',      'App.jsx\n(Router)',     230, 100, C_BLUE_LIGHT,   C_BLUE),
        ('home',     'Home Page',             90,  170, C_ORANGE_LIGHT, C_ORANGE),
        ('tripdet',  'Trip Detail',           230, 170, C_ORANGE_LIGHT, C_ORANGE),
        ('daypage',  'Day Page',              370, 170, C_ORANGE_LIGHT, C_ORANGE),
        ('chat',     'FloatingChat\n(AI)',    490, 100, C_PURPLE_LIGHT, C_PURPLE),
        ('apiutil',  'api.js\n(HTTP Client)', 230, 250, C_GRAY_LIGHT,   C_GRAY),
        ('server',   'server/index.js',       230, 330, C_BLUE,         C_WHITE),
        ('trips_r',  'trips route',           80,  410, C_GREEN_LIGHT,  C_GREEN),
        ('chat_r',   'chat route',            230, 410, C_GREEN_LIGHT,  C_GREEN),
        ('weather_r','weather route',         380, 410, C_TEAL_LIGHT,   C_TEAL),
        ('places_r', 'places route',          510, 410, C_TEAL_LIGHT,   C_TEAL),
        ('storage',  'storage.js\n(JSON)',    80,  490, C_ORANGE_LIGHT, C_ORANGE),
        ('gemini',   'Gemini AI',             230, 490, C_PURPLE_LIGHT, C_PURPLE),
        ('owm',      'OpenWeatherMap',        380, 490, C_TEAL_LIGHT,   C_TEAL),
        ('gplaces',  'Google Places',         510, 490, C_TEAL_LIGHT,   C_TEAL),
    ]

    arrows = [
        ('browser', 'app', ''),
        ('app', 'home', 'navigates to'),
        ('app', 'tripdet', 'navigates to'),
        ('app', 'daypage', 'navigates to'),
        ('app', 'chat', 'always visible'),
        ('home', 'apiutil', 'fetch trips'),
        ('tripdet', 'apiutil', 'fetch trip'),
        ('daypage', 'apiutil', 'fetch day data'),
        ('chat', 'apiutil', 'send message'),
        ('apiutil', 'server', 'HTTP requests'),
        ('server', 'trips_r', ''),
        ('server', 'chat_r', ''),
        ('server', 'weather_r', ''),
        ('server', 'places_r', ''),
        ('trips_r', 'storage', 'read/write JSON'),
        ('chat_r', 'gemini', 'AI call'),
        ('weather_r', 'owm', 'API call'),
        ('places_r', 'gplaces', 'API call'),
    ]

    elems.append(ConnectionDiagram(boxes, arrows, width=CONTENT_W))
    elems.append(Spacer(1, 0.2*inch))

    body = ParagraphStyle('Body', fontName='Helvetica', fontSize=9.5,
                           textColor=C_SLATE, leading=15)
    elems.append(Paragraph(
        '<b>Key insight:</b> The browser never talks directly to Gemini AI, Google Maps, or '
        'OpenWeatherMap. Everything goes through <b>server/index.js</b> which acts as a secure '
        'middleman — keeping your API keys hidden from the public internet.', body))

    elems.append(PageBreak())
    return elems


def flowchart_page(styles):
    elems = []
    elems.append(Spacer(1, 0.2*inch))
    elems.append(SectionHeader('How It Works: Step-by-Step Flow', C_TEAL))
    elems.append(Spacer(1, 0.1*inch))

    note_style = ParagraphStyle('Note', fontName='Helvetica', fontSize=9.5,
                                  textColor=C_GRAY, spaceAfter=10, leading=15)
    elems.append(Paragraph('What happens from the moment you open Trip Wizard to getting a response:', note_style))

    # Left column: Opening the app
    steps_left = [
        ('You open http://localhost:5173 in your browser', 'start'),
        ('React app loads — App.jsx sets up page routing', 'action'),
        ('Home page fetches your saved trips from the server', 'action'),
        ('Server reads trips.json file and sends the list back', 'action'),
        ('Your trips appear on screen as cards', 'action'),
    ]

    steps_right = [
        ('You click "Ask AI" on a Day page', 'start'),
        ('FloatingChat sends your question + trip/day context', 'action'),
        ('Server looks up your trip and current weather', 'action'),
        ('Is a Gemini API key configured?', 'decision'),
        ('Gemini AI reads full context and generates a reply', 'action'),
        ('OR: Demo mode returns a canned helpful response', 'action'),
        ('Reply appears in the chat panel', 'end'),
    ]

    col_w = (CONTENT_W - 20) / 2

    hdr_style = ParagraphStyle('FlowHdr', fontName='Helvetica-Bold', fontSize=10,
                                textColor=C_BLUE, spaceBefore=4, spaceAfter=6)
    elems.append(Paragraph('Flow A: Opening the app & loading trips', hdr_style))
    elems.append(FlowchartBox(steps_left, width=CONTENT_W))
    elems.append(Spacer(1, 0.2*inch))
    elems.append(Paragraph('Flow B: Asking the AI assistant a question', hdr_style))
    elems.append(FlowchartBox(steps_right, width=CONTENT_W))

    elems.append(PageBreak())
    return elems


def file_deep_dives(styles):
    body = ParagraphStyle('Body', fontName='Helvetica', fontSize=10,
                           textColor=C_SLATE, leading=16, spaceAfter=8)
    bold_body = ParagraphStyle('BoldBody', fontName='Helvetica-Bold', fontSize=10,
                                textColor=C_SLATE, leading=16, spaceAfter=4)
    bullet = ParagraphStyle('Bullet', fontName='Helvetica', fontSize=10,
                              textColor=C_SLATE, leading=16, leftIndent=16,
                              bulletIndent=6, spaceAfter=4)
    sub_hdr = ParagraphStyle('SubHdr', fontName='Helvetica-Bold', fontSize=12,
                               textColor=C_BLUE, spaceBefore=8, spaceAfter=4)
    label_style = ParagraphStyle('Label', fontName='Helvetica-Bold', fontSize=9,
                                   textColor=C_GRAY, spaceAfter=2)

    def section(title, color, purpose, why, steps, glossary_terms=None):
        items = []
        items.append(Spacer(1, 0.15*inch))

        # Colored header strip
        drawing = Drawing(CONTENT_W, 38)
        bg = Rect(0, 0, CONTENT_W, 38, fillColor=color, strokeColor=None)
        drawing.add(bg)
        lbl = String(12, 14, title, fontName='Helvetica-Bold', fontSize=14, fillColor=colors.white)
        drawing.add(lbl)
        items.append(drawing)
        items.append(Spacer(1, 0.1*inch))

        items.append(Paragraph('<b>Purpose:</b> ' + purpose, body))
        items.append(Paragraph('<b>Why this file exists:</b> ' + why, body))
        items.append(Spacer(1, 0.05*inch))
        items.append(Paragraph('What it does:', bold_body))
        for step in steps:
            items.append(Paragraph('• ' + step, bullet))

        if glossary_terms:
            items.append(Spacer(1, 0.1*inch))
            items.append(GlossaryBox(glossary_terms, width=CONTENT_W))

        return items

    elems = []
    elems.append(Spacer(1, 0.2*inch))
    elems.append(SectionHeader('File Deep Dives', C_ORANGE))

    # server/index.js
    elems += section(
        'server/index.js  —  The Server Entry Point', C_BLUE,
        'This file starts the web server that powers the entire app behind the scenes.',
        'The frontend (what you see) can\'t talk to AI or weather services directly — those require secret API keys. This file creates a secure middleman server that handles those requests.',
        [
            'Loads all the API keys from the .env configuration file',
            'Creates an Express web server on port 3001',
            'Registers four route handlers: trips, chat, weather, and places',
            'Starts listening for incoming requests from the browser',
            'Prints a startup summary showing which API keys are configured',
        ],
        [('Express', 'A popular toolkit for building web servers in JavaScript'),
         ('Port', 'A numbered "door" on your computer where the server listens for requests'),
         ('Route', 'A specific web address pattern that triggers a specific action'),
         ('CORS', 'A security rule that controls which websites can talk to this server')]
    )

    # server/db/storage.js
    elems += section(
        'server/db/storage.js  —  The Data Store', C_ORANGE,
        'This file is responsible for reading and writing all trip data to a file on your computer.',
        'Rather than using a complex database system, Trip Wizard saves all your trips as a simple JSON file (trips.json). This keeps the project lightweight and easy to run locally.',
        [
            'Provides functions to get all trips, get one trip by ID, create, update, and delete trips',
            'Also provides functions to add, update, and remove individual day entries within a trip',
            'Every read/write goes through this file, keeping all data logic in one place',
            'Automatically creates the data file if it doesn\'t exist yet',
        ],
        [('JSON', 'A text format that looks like {"key": "value"} — easy for computers to read'),
         ('CRUD', 'Create, Read, Update, Delete — the four basic database operations'),
         ('Function', 'A named set of instructions the program can reuse')]
    )

    # server/services/gemini.js
    elems += section(
        'server/services/gemini.js  —  The AI Brain', C_PURPLE,
        'This file handles all communication with Google\'s Gemini AI — both the chat assistant and the schedule optimizer.',
        'The AI needs a lot of context (your trip details, weather, planned activities) formatted in a specific way. This file builds that context and handles the API communication.',
        [
            'Builds a detailed "system prompt" — a briefing that tells the AI who it is and what it knows about your trip',
            'Includes your trip name, dates, travelers, today\'s location, activities, and weather in that briefing',
            'Sends your chat message to Gemini and returns the response',
            'If the AI returns a structured travel plan (wrapped in special markers), extracts and parses that plan',
            'Runs a separate "optimize schedule" function that asks the AI to reorder activities for the best day',
            'Falls back to helpful demo responses if no API key is configured',
            'Automatically tries backup models if the main model is over its usage limit',
        ],
        [('API', 'A way for two programs to talk to each other'),
         ('System prompt', 'Background instructions given to the AI before the conversation starts'),
         ('Model', 'The specific version of the AI brain being used (e.g., gemini-2.5-flash)'),
         ('JSON parsing', 'Reading structured data from text that the AI writes back')]
    )

    # server/services/weather.js
    elems += section(
        'server/services/weather.js  —  Weather Integration', C_TEAL,
        'This file talks to the OpenWeatherMap API to get real-time weather and 5-day forecasts.',
        'Weather data requires a specialized third-party service. This file encapsulates that complexity so the rest of the app can simply call "get weather for Paris" without worrying about the details.',
        [
            'Converts a city name (like "Paris, France") into GPS coordinates using OpenWeatherMap\'s geocoding service',
            'Fetches the current weather conditions at that location',
            'Fetches a 5-day hourly forecast and groups it by day, extracting min/max temperatures and rain probability',
            'Returns detailed weather objects (temperature, humidity, wind speed, rain chance)',
            'Falls back to realistic mock weather data when no API key is configured',
        ],
        [('Geocoding', 'Converting a place name (like "Rome") into GPS coordinates'),
         ('API key', 'A secret password that proves you have permission to use a service'),
         ('Mock data', 'Fake but realistic data used when a real API isn\'t available')]
    )

    elems.append(PageBreak())
    elems.append(Spacer(1, 0.2*inch))
    elems.append(SectionHeader('File Deep Dives (continued)', C_ORANGE))

    # client/src/App.jsx
    elems += section(
        'client/src/App.jsx  —  The Frontend Shell', C_BLUE,
        'This is the outer container of the entire web interface — it sets up navigation and wraps everything in the global chat state.',
        'React applications need a single "root" component that decides which page to show based on the URL. This is that component.',
        [
            'Wraps the entire app in ChatProvider so any page can open/close the AI chat',
            'Renders the Navbar at the top of every page',
            'Uses React Router to map URL patterns to page components (/ = Home, /trips/:id = Trip Detail, etc.)',
            'Renders the FloatingChat button/panel so it\'s always accessible no matter which page you\'re on',
        ],
        [('React Router', 'A library that shows different pages based on what\'s in the browser URL bar'),
         ('Component', 'A reusable building block of the user interface'),
         ('Context', 'A way to share data (like chat state) across all components without passing it manually')]
    )

    # client/src/pages/DayPage.jsx
    elems += section(
        'client/src/pages/DayPage.jsx  —  The Day View', C_ORANGE,
        'The most feature-rich page — shows all the details for a single travel day: activities, weather, nearby places, and the visual timeline.',
        'A travel day has many dimensions (what to do, where to eat, what the weather is, what\'s open nearby). This page brings all those pieces together in a single organized view.',
        [
            'Loads the trip and the specific day entry from the server when the page opens',
            'Shows the date, location, and accommodation at the top',
            'Always displays the WeatherWidget for the day\'s location',
            'On mobile: shows tabs to switch between "Plan" and "Places" views',
            'On desktop: shows Plan and Places side by side in two columns',
            'The Plan column contains an Activity Editor (add/remove activities) and the Timeline',
            'The Places column shows the PlacesPanel for discovering what\'s nearby',
            'The "Ask AI" button opens the chat panel with full day context pre-loaded',
        ]
    )

    # client/src/components/FloatingChat.jsx
    elems += section(
        'client/src/components/FloatingChat.jsx  —  The AI Chat Panel', C_PURPLE,
        'This is the floating chat interface in the bottom-right corner — the main way users interact with the AI assistant.',
        'The chat needs to be available on every page and always know where the user is in the app (which trip, which day) so the AI has proper context.',
        [
            'Reads the current URL to figure out if you\'re viewing a trip or a specific day',
            'Passes that context (tripId, dayId) with every message so the AI knows your situation',
            'Sends your message to the server, which forwards it to Gemini AI with full trip context',
            'Displays the conversation with user messages on the right and AI responses on the left',
            'Shows a notification badge on the wizard button when there are unread AI replies',
            'When AI returns a structured travel plan, displays it as an interactive "Plan Card" you can approve',
            'Shows quick suggestion buttons ("Find a restaurant", "What to pack?") for first-time users',
        ],
        [('State', 'Data that can change over time and causes the UI to update when it does'),
         ('Context', 'The URL-derived information about which trip/day you\'re looking at'),
         ('Async', 'Operations that happen in the background without freezing the page')]
    )

    # client/src/components/Timeline.jsx
    elems += section(
        'client/src/components/Timeline.jsx  —  The Visual Timeline', C_GREEN,
        'Displays your planned activities as a visual timeline and provides the AI schedule optimization feature.',
        'A plain list of activities is hard to reason about. A timeline shows you the flow of the day and makes it easy to spot gaps, conflicts, or inefficient ordering.',
        [
            'Shows activities sorted by time as a vertical timeline with dots and connecting lines',
            'Each activity card shows the time, name, duration, weather suitability icon, and crowd level badge',
            'Has an "AI Optimize" button that sends your activities to the AI for smart reordering',
            'The AI returns an optimized schedule with explanations for each time slot',
            'Shows a "Tips" section below the optimized schedule with practical advice',
            'Can toggle between the original manual order and the AI-optimized order',
        ],
        [('Crowd level', 'An AI estimate of how busy a location typically is (low/medium/high)'),
         ('Weather suitability', 'Whether an activity is better suited for good or bad weather')]
    )

    elems.append(PageBreak())
    return elems


def walkthroughs_page(styles):
    body = ParagraphStyle('Body', fontName='Helvetica', fontSize=10,
                           textColor=C_SLATE, leading=16, spaceAfter=8)
    step_hdr = ParagraphStyle('StepHdr', fontName='Helvetica-Bold', fontSize=10,
                               textColor=C_SLATE, leading=16, spaceBefore=4, spaceAfter=2)
    scenario_hdr = ParagraphStyle('ScenHdr', fontName='Helvetica-Bold', fontSize=13,
                                   textColor=C_WHITE, spaceBefore=0, spaceAfter=6)
    italic_note = ParagraphStyle('ItalicNote', fontName='Helvetica-Oblique', fontSize=9,
                                   textColor=C_GRAY, spaceAfter=8)

    def numbered_steps(steps):
        items = []
        for i, (step, detail) in enumerate(steps, 1):
            row_bg = C_BLUE_LIGHT if i % 2 == 0 else C_WHITE
            row = Table(
                [[Paragraph(f'<b>{i}.</b>', step_hdr),
                  Paragraph(f'<b>{step}</b>', step_hdr)]],
                colWidths=[24, CONTENT_W - 24]
            )
            row.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), row_bg),
                ('TOPPADDING', (0,0), (-1,-1), 4),
                ('BOTTOMPADDING', (0,0), (-1,-1), 2),
                ('LEFTPADDING', (0,0), (-1,-1), 6),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ]))
            items.append(row)
            if detail:
                detail_row = Table(
                    [['', Paragraph(detail, body)]],
                    colWidths=[24, CONTENT_W - 24]
                )
                detail_row.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), row_bg),
                    ('TOPPADDING', (0,0), (-1,-1), 0),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 5),
                    ('LEFTPADDING', (0,0), (-1,-1), 6),
                    ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ]))
                items.append(detail_row)
        return items

    elems = []
    elems.append(Spacer(1, 0.2*inch))
    elems.append(SectionHeader('Example Walkthroughs', C_BLUE))
    elems.append(Spacer(1, 0.1*inch))
    elems.append(Paragraph(
        'Here\'s exactly what happens under the hood when you use Trip Wizard.', body))

    # ── Scenario 1 ──
    s1_drawing = Drawing(CONTENT_W, 38)
    s1_drawing.add(Rect(0, 0, CONTENT_W, 38, fillColor=C_BLUE, strokeColor=None))
    s1_drawing.add(String(12, 14, 'Scenario 1: Creating a new trip to Tokyo', fontName='Helvetica-Bold', fontSize=13, fillColor=colors.white))
    elems.append(s1_drawing)
    elems.append(Spacer(1, 0.1*inch))

    s1_steps = [
        ('You click "Plan a New Trip"',
         'Home.jsx detects the click and shows the TripForm component with fields for name, destination, dates, and travelers.'),
        ('You fill in: "Tokyo Adventure", destination "Tokyo", dates March 10–17, 2 travelers',
         'TripForm validates that the required fields are filled in.'),
        ('You click "Create Trip"',
         'Home.jsx calls api.js → which sends a POST /api/trips request to the server.'),
        ('server/routes/trips.js receives the request',
         'It generates a unique ID for the trip, adds a timestamp, and calls storage.js → addTrip().'),
        ('storage.js reads trips.json, appends the new trip, and saves the file',
         'The complete trip object (with its new ID) is returned back up the chain.'),
        ('api.js receives the response and passes it to Home.jsx',
         'Home.jsx adds the new trip to the top of the list without reloading the page.'),
        ('You see "Tokyo Adventure" appear as a card on screen',
         'Your data: {"id": "abc123", "name": "Tokyo Adventure", "destination": "Tokyo", "startDate": "2025-03-10", "endDate": "2025-03-17", "travelers": [...]}'),
    ]
    elems += numbered_steps(s1_steps)
    elems.append(Spacer(1, 0.2*inch))

    # ── Scenario 2 ──
    s2_drawing = Drawing(CONTENT_W, 38)
    s2_drawing.add(Rect(0, 0, CONTENT_W, 38, fillColor=C_GREEN, strokeColor=None))
    s2_drawing.add(String(12, 14, 'Scenario 2: Getting an AI-optimized schedule', fontName='Helvetica-Bold', fontSize=13, fillColor=colors.white))
    elems.append(s2_drawing)
    elems.append(Spacer(1, 0.1*inch))

    s2_steps = [
        ('You\'re on the Day page for March 12 in Tokyo — you\'ve added 4 activities',
         'Activities: "Tsukiji Market", "Senso-ji Temple", "Shibuya Crossing", "TeamLab Museum"'),
        ('You click "✨ AI Optimize" in the Timeline component',
         'Timeline.jsx calls api.js → POST /api/chat/optimize with the tripId and dayId.'),
        ('server/routes/chat.js looks up your trip and day from storage.js',
         'It also calls weather.js to get the current weather for Tokyo.'),
        ('server/services/gemini.js builds the optimization prompt',
         'The prompt includes all 4 activities, Tokyo weather (e.g., "partly cloudy, 14-19°C, 20% rain"), and instructions about opening hours and crowd patterns.'),
        ('Gemini AI thinks about the best order',
         'It reasons: markets are best early morning, temples midday, indoor experiences (TeamLab) if rain increases, famous crossings at dusk for atmosphere.'),
        ('Gemini returns a JSON schedule',
         '"08:00 Tsukiji Market (low crowds), 10:30 Senso-ji Temple, 13:30 TeamLab Museum, 17:30 Shibuya Crossing (sunset golden hour)"'),
        ('The optimized schedule appears in your Timeline',
         'Each activity card shows weather suitability (☀️/⛅/🌧️), crowd level badge, and a note explaining why that time is optimal.'),
    ]
    elems += numbered_steps(s2_steps)
    elems.append(PageBreak())

    # ── Scenario 3 ──
    elems.append(Spacer(1, 0.2*inch))
    elems.append(SectionHeader('Example Walkthroughs (continued)', C_BLUE))
    elems.append(Spacer(1, 0.1*inch))

    s3_drawing = Drawing(CONTENT_W, 38)
    s3_drawing.add(Rect(0, 0, CONTENT_W, 38, fillColor=C_PURPLE, strokeColor=None))
    s3_drawing.add(String(12, 14, 'Scenario 3: Asking the AI to plan your remaining days', fontName='Helvetica-Bold', fontSize=13, fillColor=colors.white))
    elems.append(s3_drawing)
    elems.append(Spacer(1, 0.1*inch))

    s3_steps = [
        ('You\'ve planned 2 of your 7 Tokyo days and you type: "Plan the remaining 5 days for me"',
         'FloatingChat.jsx reads the current URL to identify your tripId and dayId, then sends this to the server.'),
        ('server/routes/chat.js assembles full trip context',
         'It includes: all 7 trip days, which 2 are already planned, the remaining 5 unplanned dates, and current weather.'),
        ('server/services/gemini.js builds a special system prompt',
         'The AI is told: "You have Tokyo, March 10-17. Days March 11 and 12 are planned. Plan March 13-17. Include a JSON plan block."'),
        ('Gemini writes a conversational reply AND a structured JSON plan at the end',
         'The JSON is wrapped in [PLAN_START] ... [PLAN_END] markers so the app can extract it.'),
        ('parsePlanFromResponse() in gemini.js extracts the plan',
         'It separates the human-readable text from the machine-readable JSON plan data.'),
        ('FloatingChat.jsx receives both the text and the plan',
         'It renders the text as a normal chat message AND shows a PlanCard below it with a preview of all 5 days.'),
        ('You review the plan and click "Add to Itinerary"',
         'PlanCard.jsx calls api.js → POST /api/trips/:id/days/batch — all 5 day entries are saved at once. Your trip calendar fills up!'),
    ]
    elems += numbered_steps(s3_steps)

    elems.append(Spacer(1, 0.3*inch))

    # Closing note
    closing_drawing = Drawing(CONTENT_W, 60)
    closing_drawing.add(Rect(0, 0, CONTENT_W, 60, fillColor=C_GRAY_LIGHT, strokeColor=None))
    closing_drawing.add(Rect(0, 0, 5, 60, fillColor=C_BLUE, strokeColor=None))
    closing_drawing.add(String(18, 36, 'The goal: less time planning, more time enjoying.',
                               fontName='Helvetica-Bold', fontSize=13, fillColor=C_SLATE))
    closing_drawing.add(String(18, 18, 'Trip Wizard handles the logistics so you can focus on the experience.',
                               fontName='Helvetica', fontSize=10, fillColor=C_GRAY))
    elems.append(closing_drawing)

    return elems


# ─── Main ────────────────────────────────────────────────────────────────────

def build_pdf():
    doc = SimpleDocTemplate(
        OUTPUT_PATH,
        pagesize=letter,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN + 0.1*inch,
        bottomMargin=MARGIN,
    )

    styles = getSampleStyleSheet()

    story = []
    story += cover_page(styles)
    story += what_it_does_page(styles)
    story += project_map_page(styles)
    story += connections_page(styles)
    story += flowchart_page(styles)
    story += file_deep_dives(styles)
    story += walkthroughs_page(styles)

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    print(f'PDF saved to: {OUTPUT_PATH}')


if __name__ == '__main__':
    build_pdf()
